name: pricecheck_ph
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  intl: ^0.18.0
  collection: ^1.19.0
  sqflite: ^2.3.0
  mobile_scanner: ^2.0.0
  path: ^1.8.3
  file_picker: ^5.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/products.json
